name: CI_for_muscle-gain
on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '2.6.x' ]

    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby version
      uses: actions/setup-ruby@master
      with:
        version: ${{ matrix.ruby }}